/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ClinicRouteImport } from './routes/clinic'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HairTreatmentsRouteImport } from './routes/hair-treatments'
import { Route as SkinTreatmentsRouteImport } from './routes/skin-treatments'
import { Route as TreatmentsSlugRouteImport } from './routes/treatments.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicRoute = ClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HairTreatmentsRoute = HairTreatmentsRouteImport.update({
  id: '/hair-treatments',
  path: '/hair-treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinTreatmentsRoute = SkinTreatmentsRouteImport.update({
  id: '/skin-treatments',
  path: '/skin-treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsSlugRoute = TreatmentsSlugRouteImport.update({
  id: '/treatments/$slug',
  path: '/treatments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clinic': typeof ClinicRoute
  '/contact': typeof ContactRoute
  '/hair-treatments': typeof HairTreatmentsRoute
  '/skin-treatments': typeof SkinTreatmentsRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clinic': typeof ClinicRoute
  '/contact': typeof ContactRoute
  '/hair-treatments': typeof HairTreatmentsRoute
  '/skin-treatments': typeof SkinTreatmentsRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clinic': typeof ClinicRoute
  '/contact': typeof ContactRoute
  '/hair-treatments': typeof HairTreatmentsRoute
  '/skin-treatments': typeof SkinTreatmentsRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clinic'
    | '/contact'
    | '/hair-treatments'
    | '/skin-treatments'
    | '/treatments/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clinic'
    | '/contact'
    | '/hair-treatments'
    | '/skin-treatments'
    | '/treatments/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/clinic'
    | '/contact'
    | '/hair-treatments'
    | '/skin-treatments'
    | '/treatments/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClinicRoute: typeof ClinicRoute
  ContactRoute: typeof ContactRoute
  HairTreatmentsRoute: typeof HairTreatmentsRoute
  SkinTreatmentsRoute: typeof SkinTreatmentsRoute
  TreatmentsSlugRoute: typeof TreatmentsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic': {
      id: '/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof ClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-treatments': {
      id: '/hair-treatments'
      path: '/hair-treatments'
      fullPath: '/hair-treatments'
      preLoaderRoute: typeof HairTreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skin-treatments': {
      id: '/skin-treatments'
      path: '/skin-treatments'
      fullPath: '/skin-treatments'
      preLoaderRoute: typeof SkinTreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/$slug': {
      id: '/treatments/$slug'
      path: '/treatments/$slug'
      fullPath: '/treatments/$slug'
      preLoaderRoute: typeof TreatmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClinicRoute: ClinicRoute,
  ContactRoute: ContactRoute,
  HairTreatmentsRoute: HairTreatmentsRoute,
  SkinTreatmentsRoute: SkinTreatmentsRoute,
  TreatmentsSlugRoute: TreatmentsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
