/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as TreatmentsIndexRouteImport } from './routes/treatments.index'
import { Route as TreatmentsSlugRouteImport } from './routes/treatments.$slug'
import { Route as TreatmentsCategoryCategoryRouteImport } from './routes/treatments.category.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRoute = TreatmentsIndexRouteImport.update({
  id: '/treatments/',
  path: '/treatments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsSlugRoute = TreatmentsSlugRouteImport.update({
  id: '/treatments/$slug',
  path: '/treatments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsCategoryCategoryRoute =
  TreatmentsCategoryCategoryRouteImport.update({
    id: '/treatments/category/$category',
    path: '/treatments/category/$category',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/treatments/': typeof TreatmentsIndexRoute
  '/treatments/category/$category': typeof TreatmentsCategoryCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/treatments': typeof TreatmentsIndexRoute
  '/treatments/category/$category': typeof TreatmentsCategoryCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/treatments/': typeof TreatmentsIndexRoute
  '/treatments/category/$category': typeof TreatmentsCategoryCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/treatments/$slug'
    | '/treatments/'
    | '/treatments/category/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/treatments/$slug'
    | '/treatments'
    | '/treatments/category/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/treatments/$slug'
    | '/treatments/'
    | '/treatments/category/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  TreatmentsSlugRoute: typeof TreatmentsSlugRoute
  TreatmentsIndexRoute: typeof TreatmentsIndexRoute
  TreatmentsCategoryCategoryRoute: typeof TreatmentsCategoryCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/treatments'
      fullPath: '/treatments/'
      preLoaderRoute: typeof TreatmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/$slug': {
      id: '/treatments/$slug'
      path: '/treatments/$slug'
      fullPath: '/treatments/$slug'
      preLoaderRoute: typeof TreatmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/category/$category': {
      id: '/treatments/category/$category'
      path: '/treatments/category/$category'
      fullPath: '/treatments/category/$category'
      preLoaderRoute: typeof TreatmentsCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  TreatmentsSlugRoute: TreatmentsSlugRoute,
  TreatmentsIndexRoute: TreatmentsIndexRoute,
  TreatmentsCategoryCategoryRoute: TreatmentsCategoryCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
